import React, { useState } from "react";
import MainLayout from "@/components/layout/MainLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Building,
  QrCode,
  Users,
  Settings as SettingsIcon,
  Download,
  BarChart3,
  Clock,
  UserCheck,
  ArrowUpRight,
  Shield,
  Sparkles,
  Camera,
  FileText,
  UserRoundCog,
  Car,
  Mail,
  CreditCard,
  IdCard,
  CheckCircle2,
  XCircle,
  Phone
} from "lucide-react";
import { useToast } from "@/components/ui/use-toast";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";

// Mock data for dashboard
const visitorData = [
  { id: 1, name: "John Doe", purpose: "Meeting", time: "10:30 AM", date: "2025-04-17", status: "Checked Out" },
  { id: 2, name: "Jane Smith", purpose: "Interview", time: "11:45 AM", date: "2025-04-17", status: "Active" },
  { id: 3, name: "Alex Wong", purpose: "Delivery", time: "09:15 AM", date: "2025-04-17", status: "Active" },
];

// Plan features
const basicPlanFeatures = [
  "50 monthly visitors",
  "Basic analytics",
  "1 entry point",
  "Email notifications",
  "30 days data retention"
];

const premiumPlanFeatures = [
  "Unlimited visitors",
  "Advanced analytics",
  "Multiple entry points",
  "SMS notifications",
  "Visitor pre-registration",
  "API access",
  "1 year data retention"
];

const Dashboard = () => {
  const [currentPlan] = useState("Basic");
  const { toast } = useToast();
  
  // Visitor field configuration
  const [visitorFields, setVisitorFields] = useState([
    { id: 1, name: "name", label: "Full Name", required: true, available: true, premium: false },
    { id: 2, name: "phone", label: "Phone Number", required: true, available: true, premium: false },
    { id: 3, name: "signature", label: "Digital Signature", required: true, available: true, premium: false, autoGenerated: true },
    { id: 4, name: "idNumber", label: "ID Number", required: false, available: true, premium: false },
    { id: 5, name: "email", label: "Email Address", required: false, available: true, premium: false },
    { id: 6, name: "facePhoto", label: "Face Photo", required: false, available: false, premium: true },
    { id: 7, name: "idPhoto", label: "ID Photo", required: false, available: false, premium: true },
    { id: 8, name: "purpose", label: "Purpose of Visit", required: false, available: false, premium: true },
    { id: 9, name: "department", label: "Department", required: false, available: false, premium: true },
    { id: 10, name: "visitingPerson", label: "Person Being Visited", required: false, available: false, premium: true },
    { id: 11, name: "vehicle", label: "Vehicle Registration Number", required: false, available: false, premium: true },
  ]);
  
  const handleDownloadQR = () => {
    toast({
      title: "QR Code Downloaded",
      description: "Your premise QR code has been downloaded successfully."
    });
  };

  const handleToggleField = (id: number) => {
    setVisitorFields(visitorFields.map(field => 
      field.id === id ? { ...field, required: !field.required } : field
    ));
  };

  const handleUpgradePrompt = () => {
    toast({
      title: "Premium Feature",
      description: "Upgrade to Premium to unlock all visitor information fields",
      action: (
        <Button className="bg-scode-blue hover:bg-scode-blue/90" size="sm">
          Upgrade
        </Button>
      )
    });
  };

  const [premiseFields, setPremiseFields] = useState([
    { id: 1, name: "name", label: "Full Name", required: true },
    { id: 2, name: "phone", label: "Phone Number", required: true },
    { id: 3, name: "visitingPerson", label: "Person Being Visited", required: true },
    { id: 4, name: "purpose", label: "Purpose of Visit", required: true },
  ]);
  
  return (
    <MainLayout>
      <div className="container mx-auto p-6">
        <h1 className="text-2xl font-bold mb-6">Premise Dashboard</h1>
        
        <div className="grid gap-6 md:grid-cols-3 mb-6">
          <Card className="bg-secondary border-white/10">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Total Visitors</CardTitle>
              <div className="text-2xl font-bold">135</div>
            </CardHeader>
            <CardContent>
              <p className="text-xs text-white/60">+12% from last month</p>
            </CardContent>
          </Card>
          
          <Card className="bg-secondary border-white/10">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Active Visitors</CardTitle>
              <div className="text-2xl font-bold">7</div>
            </CardHeader>
            <CardContent>
              <p className="text-xs text-white/60">Currently in your premise</p>
            </CardContent>
          </Card>
          
          <Card className="bg-secondary border-white/10">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-medium">Average Visit Time</CardTitle>
              <div className="text-2xl font-bold">47m</div>
            </CardHeader>
            <CardContent>
              <p className="text-xs text-white/60">-5% from last week</p>
            </CardContent>
          </Card>
        </div>
        
        <Tabs defaultValue="visitors" className="space-y-4">
          <TabsList>
            <TabsTrigger value="visitors" className="flex items-center">
              <Users className="w-4 h-4 mr-2" />
              Visitors
            </TabsTrigger>
            <TabsTrigger value="qrcode" className="flex items-center">
              <QrCode className="w-4 h-4 mr-2" />
              QR Codes
            </TabsTrigger>
            <TabsTrigger value="analytics" className="flex items-center">
              <BarChart3 className="w-4 h-4 mr-2" />
              Analytics
            </TabsTrigger>
            <TabsTrigger value="settings" className="flex items-center">
              <SettingsIcon className="w-4 h-4 mr-2" />
              Settings
            </TabsTrigger>
          </TabsList>
          
          <TabsContent value="visitors" className="space-y-4">
            <Card className="bg-secondary border-white/10">
              <CardHeader>
                <CardTitle className="text-xl">Recent Visitors</CardTitle>
                <CardDescription>
                  Track and manage visitors to your premise
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="rounded-md border border-white/10">
                  <div className="relative w-full overflow-auto">
                    <table className="w-full caption-bottom text-sm">
                      <thead className="[&_tr]:border-b">
                        <tr className="border-b border-white/10 transition-colors hover:bg-secondary/20">
                          <th className="h-10 px-4 text-left align-middle font-medium text-white">Name</th>
                          <th className="h-10 px-4 text-left align-middle font-medium text-white">Purpose</th>
                          <th className="h-10 px-4 text-left align-middle font-medium text-white">Time</th>
                          <th className="h-10 px-4 text-left align-middle font-medium text-white">Status</th>
                          <th className="h-10 px-4 text-left align-middle font-medium text-white"></th>
                        </tr>
                      </thead>
                      <tbody>
                        {visitorData.map((visitor) => (
                          <tr 
                            key={visitor.id}
                            className="border-b border-white/10 transition-colors hover:bg-white/5"
                          >
                            <td className="p-4 align-middle">{visitor.name}</td>
                            <td className="p-4 align-middle">{visitor.purpose}</td>
                            <td className="p-4 align-middle">
                              <div className="flex flex-col">
                                <span>{visitor.time}</span>
                                <span className="text-xs text-white/60">{visitor.date}</span>
                              </div>
                            </td>
                            <td className="p-4 align-middle">
                              <div className={`inline-flex items-center px-2 py-1 rounded-full text-xs ${
                                visitor.status === "Active" ? "bg-green-500/20 text-green-500" : "bg-white/10 text-white/60"
                              }`}>
                                <span className={`w-1.5 h-1.5 rounded-full mr-1 ${
                                  visitor.status === "Active" ? "bg-green-500" : "bg-white/60"
                                }`}></span>
                                {visitor.status}
                              </div>
                            </td>
                            <td className="p-4 align-middle">
                              <Button variant="ghost" size="sm">
                                Details
                              </Button>
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
                <div className="mt-4 text-center">
                  <Button variant="outline">View All Visitors</Button>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
          
          <TabsContent value="qrcode" className="space-y-4">
            <div className="grid md:grid-cols-2 gap-6">
              <Card className="bg-secondary border-white/10">
                <CardHeader>
                  <CardTitle className="text-xl">Premise QR Code</CardTitle>
                  <CardDescription>
                    Visitors scan this QR code to check in to your premise
                  </CardDescription>
                </CardHeader>
                <CardContent className="flex flex-col items-center">
                  <div className="bg-white p-4 rounded-lg mb-6">
                    <QrCode className="w-48 h-48 text-black" />
                  </div>
                  <Button 
                    onClick={handleDownloadQR}
                    className="bg-scode-blue hover:bg-scode-blue/90"
                  >
                    <Download className="mr-2 h-4 w-4" />
                    Download QR Code
                  </Button>
                </CardContent>
              </Card>
              
              <Card className="bg-secondary border-white/10">
                <CardHeader>
                  <CardTitle className="text-xl">Required Visitor Information</CardTitle>
                  <CardDescription>
                    Customize what information visitors need to provide
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-6">
                    {/* Basic Plan Fields */}
                    <div>
                      <h3 className="font-semibold mb-2 flex items-center">
                        Basic Fields 
                        <span className="ml-2 text-xs bg-scode-blue/20 text-scode-blue px-2 py-0.5 rounded">
                          INCLUDED
                        </span>
                      </h3>
                      <div className="space-y-3">
                        {visitorFields.filter(field => !field.premium).map(field => (
                          <div key={field.id} className="flex items-center justify-between p-3 border border-white/10 rounded-md bg-white/5">
                            <div className="flex items-center">
                              {field.autoGenerated ? (
                                <div className="w-8 h-8 rounded-full bg-green-500/10 flex items-center justify-center mr-3">
                                  <CheckCircle2 className="w-4 h-4 text-green-500" />
                                </div>
                              ) : (
                                <div className="w-8 h-8 rounded-full bg-white/10 flex items-center justify-center mr-3">
                                  {field.name === "name" && <UserCheck className="w-4 h-4 text-white" />}
                                  {field.name === "phone" && <Phone className="w-4 h-4 text-white" />}
                                  {field.name === "idNumber" && <IdCard className="w-4 h-4 text-white" />}
                                  {field.name === "email" && <Mail className="w-4 h-4 text-white" />}
                                </div>
                              )}
                              <div>
                                <p className="font-medium">{field.label}</p>
                                <p className="text-xs text-white/60">
                                  {field.autoGenerated ? "Auto-generated" : field.required ? "Required" : "Optional"}
                                </p>
                              </div>
                            </div>
                            
                            {!field.autoGenerated && (
                              <div className="flex items-center">
                                <Label htmlFor={`required-${field.id}`} className="mr-2 text-sm">
                                  {field.required ? "Required" : "Optional"}
                                </Label>
                                <Switch
                                  id={`required-${field.id}`}
                                  checked={field.required}
                                  onCheckedChange={() => handleToggleField(field.id)}
                                  disabled={field.name === "name" || field.name === "phone"} // These are always required
                                />
                              </div>
                            )}
                          </div>
                        ))}
                      </div>
                    </div>

                    <Separator className="border-white/10" />

                    {/* Premium Plan Fields */}
                    <div>
                      <h3 className="font-semibold mb-2 flex items-center">
                        Premium Fields 
                        <span className="ml-2 text-xs bg-amber-500/20 text-amber-500 px-2 py-0.5 rounded flex items-center">
                          <Sparkles className="w-3 h-3 mr-1" /> PREMIUM
                        </span>
                      </h3>
                      <div className="space-y-3">
                        {visitorFields.filter(field => field.premium).map(field => (
                          <div key={field.id} 
                            className="flex items-center justify-between p-3 border border-white/10 rounded-md bg-white/5 opacity-80"
                            onClick={handleUpgradePrompt}
                          >
                            <div className="flex items-center">
                              <div className="w-8 h-8 rounded-full bg-white/10 flex items-center justify-center mr-3">
                                {field.name === "facePhoto" && <Camera className="w-4 h-4 text-white" />}
                                {field.name === "idPhoto" && <IdCard className="w-4 h-4 text-white" />}
                                {field.name === "purpose" && <FileText className="w-4 h-4 text-white" />}
                                {field.name === "department" && <Building className="w-4 h-4 text-white" />}
                                {field.name === "visitingPerson" && <UserRoundCog className="w-4 h-4 text-white" />}
                                {field.name === "vehicle" && <Car className="w-4 h-4 text-white" />}
                              </div>
                              <div>
                                <p className="font-medium">{field.label}</p>
                                <p className="text-xs text-white/60">Premium feature</p>
                              </div>
                            </div>
                            
                            <Button 
                              variant="ghost" 
                              size="sm" 
                              className="text-amber-500"
                              onClick={handleUpgradePrompt}
                            >
                              <Sparkles className="w-4 h-4 mr-1" />
                              Unlock
                            </Button>
                          </div>
                        ))}
                      </div>

                      <div className="mt-4">
                        <Button 
                          className="w-full bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-600 hover:to-amber-700"
                          onClick={handleUpgradePrompt}
                        >
                          <Sparkles className="w-4 h-4 mr-2" />
                          Upgrade to Premium
                        </Button>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
          
          <TabsContent value="analytics" className="space-y-4">
            <Card className="bg-secondary border-white/10">
              <CardHeader>
                <CardTitle className="text-xl">Visitor Analytics</CardTitle>
                <CardDescription>
                  {currentPlan === "Basic" ? 
                    "Upgrade to Premium for detailed analytics" : 
                    "Detailed insights about your visitor traffic"
                  }
                </CardDescription>
              </CardHeader>
              <CardContent className="h-80 flex items-center justify-center">
                {currentPlan === "Basic" ? (
                  <div className="text-center">
                    <BarChart3 className="w-20 h-20 mx-auto opacity-40 mb-4" />
                    <p className="text-white/60 mb-4">
                      Advanced analytics are available on the Premium plan
                    </p>
                    <Button className="bg-scode-blue hover:bg-scode-blue/90">
                      Upgrade to Premium
                    </Button>
                  </div>
                ) : (
                  <div className="text-center">
                    <BarChart3 className="w-20 h-20 mx-auto opacity-40" />
                    <p className="text-white/60">
                      Analytics visualization would appear here
                    </p>
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>
          
          <TabsContent value="settings" className="space-y-4">
            <div className="grid md:grid-cols-2 gap-6">
              <Card className="bg-secondary border-white/10">
                <CardHeader>
                  <CardTitle className="text-xl">Premise Settings</CardTitle>
                  <CardDescription>
                    Configure your premise and visitor management settings
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div>
                    <h3 className="font-medium mb-2">Premise Information</h3>
                    <Button variant="outline" className="w-full text-left justify-start">
                      <Building className="mr-2 h-4 w-4" />
                      Edit Premise Details
                    </Button>
                  </div>
                  <div>
                    <h3 className="font-medium mb-2">Security Settings</h3>
                    <Button variant="outline" className="w-full text-left justify-start">
                      <Shield className="mr-2 h-4 w-4" />
                      Configure Security Options
                    </Button>
                  </div>
                  <div>
                    <h3 className="font-medium mb-2">User Management</h3>
                    <Button variant="outline" className="w-full text-left justify-start">
                      <UserCheck className="mr-2 h-4 w-4" />
                      Manage Staff Access
                    </Button>
                  </div>
                </CardContent>
              </Card>
              
              <Card className="bg-secondary border-white/10">
                <CardHeader>
                  <CardTitle className="text-xl">Your Plan</CardTitle>
                  <CardDescription>
                    Current plan: <span className="font-medium">{currentPlan}</span>
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="p-4 border border-white/10 rounded-lg">
                    <h3 className="text-lg font-medium mb-2 flex items-center">
                      {currentPlan === "Basic" ? (
                        <>Basic</>
                      ) : (
                        <>Premium <Sparkles className="ml-1 w-4 h-4 text-yellow-400" /></>
                      )}
                    </h3>
                    <ul className="space-y-2 mb-4">
                      {currentPlan === "Basic" ? 
                        basicPlanFeatures.map((feature, i) => (
                          <li key={i} className="text-sm flex items-start">
                            <span className="mr-2">✓</span> {feature}
                          </li>
                        )) : 
                        [...basicPlanFeatures, ...premiumPlanFeatures].map((feature, i) => (
                          <li key={i} className="text-sm flex items-start">
                            <span className="mr-2">✓</span> {feature}
                          </li>
                        ))
                      }
                    </ul>
                    
                    {currentPlan === "Basic" && (
                      <Button className="w-full bg-scode-blue hover:bg-scode-blue/90">
                        <Sparkles className="mr-2 h-4 w-4" />
                        Upgrade to Premium
                      </Button>
                    )}
                    
                    {currentPlan === "Premium" && (
                      <Button className="w-full" variant="outline">
                        Manage Subscription
                      </Button>
                    )}
                  </div>
                </CardContent>
              </Card>
            </div>
          </TabsContent>
        </Tabs>
      </div>
    </MainLayout>
  );
};

export default Dashboard;
