// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgxalequiljxlgfyvaff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhneGFsZXF1aWxqeGxnZnl2YWZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzgxMDEsImV4cCI6MjA2MDY1NDEwMX0.aV-3qhjXpNW0uOxZubzbb3b-WmUt1pqoqP5iTvvryDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);